server:
  port: 12000
spring:
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/eric123456/black_horse_javaee92_phase.git
          #username:   仓库如果是私有的话，就需要用户名和密码
          #password:
  rabbitmq:
    host: 192.168.66.133
management: #暴露触发消息总线的地址
  endpoints:
    web:
      exposure:
        include: bus-refresh