server:
  port: 9009
spring:
  application:
    admin: tensquare-sms
  rabbitmq:
    host: 192.168.66.133
aliyun:
  sms:
    temp_code: SMS_100735040
    sign_name: 物流系统
    accessKeyId: LTAI0DByuBGlQzS9
    accessKeySecret: OygoBAVQRuCt4vf97Nfwav2NN8gcr2